{
 "title": "Observability Fundamentals",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "90th Percentile Processing Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum without(instance, job, tier)(rate(fulfilment_processing_seconds_bucket[5m])))",
     "legendFormat": "{{instance_number}}"
    }
   ]
  },
  {
   "title": "Average Processing Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "avg by(le) (rate(fulfilment_processing_seconds_bucket[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without(instance, job) (rate(process_cpu_seconds_total{job=\"fulfilment-processor\"}[5m]))",
     "legendFormat": "i: {{instance_number}}"
    }
   ]
  },
  {
   "title": ".NET Memory Used",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dotnet_total_memory_bytes", "legendFormat": "i: {{instance_number}}" }
   ]
  },
  { "title": "Web", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": " sum by(status) (rate(http_server_requests_seconds_sum{job=\"fulfilment-api\"}[5m])) /  sum by(status) (rate(http_server_requests_seconds_count{job=\"fulfilment-api\"}[5m])) ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Active Tomcat Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 10 },
   "targets": [
    {
     "expr": "tomcat_sessions_active_current_sessions"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(instance, job, tier, id, area) (jvm_memory_used_bytes{job=\"fulfilment-api\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without(job) (rate(process_cpu_usage{job=\"fulfilment-api\"}[5m]))"
    }
   ]
  },
  { "title": "Infrastructure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Free Disk Space",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min without(mountpoint) (node_filesystem_avail_bytes) / min without(mountpoint) (node_filesystem_size_bytes)"
    }
   ]
  },
  {
   "title": "Server Memory Used",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_SReclaimable_bytes) / node_memory_MemTotal_bytes "
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without(job, cpu, mode) (rate(node_cpu_seconds_total[5m]))"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 15, "y": 19 },
   "repeat": "node",
   "yaxes": [
    { "format": "bits", "label": "bits in (-) / bits out (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$node'}[5m])*8 or irate(node_network_receive_bytes{instance=~'$node'}[5m])*8",
     "legendFormat": "{{device}}_in"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$node'}[5m])*8 or irate(node_network_transmit_bytes{instance=~'$node'}[5m])*8",
     "legendFormat": "{{device}}_out"
    }
   ]
  }
 ]
}