{
 "title": "Hackathon - Part 2",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Recent Status",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum without(job) (up{job=\"fulfilment-processor\"})",
     "legendFormat": "i: {{instance_number}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without(job) (rate(process_cpu_seconds_total{job=\"fulfilment-processor\"}[5m]))",
     "legendFormat": "i: {{instance_number}}"
    }
   ]
  },
  {
   "title": ".NET Memory Used",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{job=\"fulfilment-processor\"}",
     "legendFormat": "i: {{instance_number}}"
    }
   ]
  }
 ]
}