{
 "title": "Hackathon",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Document Rendering Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum without(instance, job)(rate(web_document_prerender_seconds_bucket[5m])))",
     "legendFormat": "{{instance_number}}"
    }
   ]
  },
  {
   "title": "Documents Rendered /s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum without(instance, job)(rate(web_document_prerender_seconds_count[5m]))",
     "legendFormat": "{{document_type}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "90th Percentile Processing Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum without(instance, job, tier)(rate(fulfilment_processing_seconds_bucket[5m])))",
     "legendFormat": "{{instance_number}}"
    }
   ]
  },
  {
   "title": "Average Processing Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "avg by(le) (rate(fulfilment_processing_seconds_bucket[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Recent Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 10 },
   "targets": [
    {
     "expr": "sum without(job) (up{job=\"fulfilment-processor\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without(instance, job) (rate(process_cpu_seconds_total{job=\"fulfilment-processor\"}[5m]))",
     "legendFormat": "i: {{instance_number}}"
    }
   ]
  },
  {
   "title": ".NET Memory Used",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{job=\"fulfilment-processor\"}",
     "legendFormat": "i: {{instance_number}}"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": " sum by(status) (rate(http_server_requests_seconds_sum{job=\"fulfilment-api\"}[5m])) /  sum by(status) (rate(http_server_requests_seconds_count{job=\"fulfilment-api\"}[5m])) ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(instance, job, tier, id, area) (jvm_memory_used_bytes{job=\"fulfilment-api\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 17, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without(job) (rate(process_cpu_usage{job=\"fulfilment-api\"}[5m]))"
    }
   ]
  }
 ]
}